# 1. App
version: '3.4'

volumes:
  pg_project:

services:
# App
  klinikreact:
    image: klinikreact
    ports:
      - "8086:8086"
    build:
      context: .
    container_name: klinikreact
    environment:
      - SPRING_R2DBC_URL=r2dbc:postgresql://host.docker.internal:5432/Klinika
      - SPRING_R2DBC_USERNAME=postgres
      - SPRING_R2DBC_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
    volumes:
      - ./src/main/resources/keys:/app/keys
      - ./src/main/resources/keystore:/app/keystore
    networks:
     - klinik_klinika-es

#Add container to network another project
networks:
  klinik_klinika-es:
    external: true