# 1. App
version: '3.4'

volumes:
  pg_project:

services:
# App
  klinikreact:
    image: klinikreact
    ports:
      - "8086:8086"
    build:
      context: .
    container_name: klinikreact
    volumes:
      - ./src/main/resources/keys:/app/keys
      - ./src/main/resources/keystore:/app/keystore
    networks:
     - klinikreact_klinikreact-es

#Add container to network another project
networks:
  klinikreact_klinikreact-es:
    external: true